[book]
authors = ["jeanbarbosa"]
language = "pt-br"
multilingual = false
src = "src"
title = "Qwerty"

[output.html]
default-theme = "light"
preferred-dark-theme = "Ayu"
smart-punctuation = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/jeanbarbosa"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/JeanBarbosa/jeanbarbosa.github.io/tree/main/{path}"
input-404 = "not-found.md"